import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Ecommerce Backend",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
