/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Subscription = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  status?: "active" | "unsubscribed" | "pending";
  subscribedAt?: string;
  unsubscribedAt?: string;
  source?: "footer" | "popup" | "checkout" | "other";
  ipAddress?: string;
  userAgent?: string;
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  rating?: number;
  title?: string;
  content?: string;
  isVerifiedPurchase?: boolean;
  status?: "pending" | "approved" | "rejected";
  helpful?: number;
  helpfulBy?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "user";
  }>;
  adminNotes?: string;
  createdAt?: string;
  updatedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
};

export type UserAccessRequest = {
  _id: string;
  _type: "userAccessRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: "pending" | "approved" | "rejected";
  requestedAt?: string;
  approvedAt?: string;
  approvedBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  rejectedAt?: string;
  rejectedBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  notes?: string;
};

export type SentNotification = {
  _id: string;
  _type: "sentNotification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notificationId?: string;
  title?: string;
  message?: string;
  type?: "promo" | "order" | "system" | "marketing" | "general";
  priority?: "low" | "medium" | "high" | "urgent";
  sentAt?: string;
  sentBy?: string;
  actionUrl?: string;
  recipientCount?: number;
  recipients?: Array<{
    email?: string;
    name?: string;
    delivered?: boolean;
    read?: boolean;
    readAt?: string;
    _key: string;
  }>;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  status?: "new" | "read" | "replied" | "closed";
  priority?: "low" | "medium" | "high" | "urgent";
  submittedAt?: string;
  ipAddress?: string;
  userAgent?: string;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  phone?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  type?: "home" | "office" | "other";
  default?: boolean;
  createdAt?: string;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  addresses?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "address";
  }>;
  preferences?: {
    newsletter?: boolean;
    emailNotifications?: boolean;
    smsNotifications?: boolean;
    preferredCurrency?: "USD" | "EUR" | "GBP" | "CAD";
    preferredLanguage?: "en" | "es" | "fr" | "de";
  };
  rewardPoints?: number;
  wishlist?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  cart?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    addedAt?: string;
    size?: string;
    color?: string;
    _key: string;
  }>;
  orders?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "order";
  }>;
  loyaltyPoints?: number;
  totalSpent?: number;
  walletBalance?: number;
  walletTransactions?: Array<{
    id?: string;
    type?:
      | "credit_refund"
      | "credit_manual"
      | "debit_order"
      | "debit_withdrawal";
    amount?: number;
    balanceBefore?: number;
    balanceAfter?: number;
    description?: string;
    orderId?: string;
    withdrawalRequestId?: string;
    processedBy?: string;
    createdAt?: string;
    status?: "completed" | "pending" | "failed" | "cancelled";
    _key: string;
  }>;
  withdrawalRequests?: Array<{
    id?: string;
    amount?: number;
    method?: "bank" | "paypal" | "stripe" | "check";
    bankDetails?: {
      accountHolderName?: string;
      bankName?: string;
      accountNumber?: string;
      routingNumber?: string;
      swiftCode?: string;
    };
    paypalEmail?: string;
    status?:
      | "pending"
      | "approved"
      | "processing"
      | "completed"
      | "rejected"
      | "cancelled";
    requestedAt?: string;
    processedAt?: string;
    processedBy?: string;
    rejectionReason?: string;
    notes?: string;
    transactionId?: string;
    _key: string;
  }>;
  lastLogin?: string;
  isActive?: boolean;
  premiumStatus?: "none" | "pending" | "active" | "rejected" | "cancelled";
  premiumAppliedAt?: string;
  premiumApprovedBy?: string;
  premiumApprovedAt?: string;
  premiumRejectedAt?: string;
  rejectionReason?: string;
  isBusiness?: boolean;
  businessStatus?: "none" | "pending" | "active" | "rejected" | "cancelled";
  businessApprovedBy?: string;
  businessApprovedAt?: string;
  businessRejectedAt?: string;
  businessAppliedAt?: string;
  membershipType?: "standard" | "premium" | "business" | "vip";
  activatedAt?: string;
  activatedBy?: string;
  isEmployee?: boolean;
  employeeRole?:
    | "callcenter"
    | "packer"
    | "warehouse"
    | "deliveryman"
    | "incharge"
    | "accounts";
  employeeStatus?: "active" | "inactive" | "suspended";
  employeeAssignedBy?: string;
  employeeAssignedAt?: string;
  employeeSuspendedBy?: string;
  employeeSuspendedAt?: string;
  employeeSuspensionReason?: string;
  employeePerformance?: {
    ordersProcessed?: number;
    ordersConfirmed?: number;
    ordersPacked?: number;
    ordersAssignedForDelivery?: number;
    ordersDelivered?: number;
    cashCollected?: number;
    paymentsReceived?: number;
    lastActiveAt?: string;
  };
  createdAt?: string;
  updatedAt?: string;
  notifications?: Array<{
    id?: string;
    title?: string;
    message?: string;
    type?: "promo" | "order" | "system" | "marketing" | "general";
    read?: boolean;
    priority?: "low" | "medium" | "high" | "urgent";
    sentAt?: string;
    readAt?: string;
    sentBy?: string;
    actionUrl?: string;
    _key: string;
  }>;
};

export type Blogcategory = {
  _id: string;
  _type: "blogcategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogcategory";
  }>;
  publishedAt?: string;
  isLatest?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    _key: string;
  }>;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "pending"
    | "address_confirmed"
    | "order_confirmed"
    | "packed"
    | "ready_for_delivery"
    | "out_for_delivery"
    | "delivered"
    | "completed"
    | "cancelled"
    | "rescheduled"
    | "failed_delivery";
  orderDate?: string;
  paymentStatus?: "pending" | "paid" | "failed" | "cancelled";
  paymentMethod?: "cash_on_delivery" | "stripe" | "card";
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "not_submitted" | "pending" | "confirmed" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?:
      | "admin"
      | "callcenter"
      | "packer"
      | "warehouse"
      | "deliveryman"
      | "incharge"
      | "accounts"
      | "system";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  status?: "new" | "hot" | "sale";
  variant?: "Light Roast" | "Medium Roast" | "Dark Roast" | "Extra Dark";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Subscription
  | Review
  | UserAccessRequest
  | SentNotification
  | Contact
  | Address
  | User
  | Blogcategory
  | Blog
  | Author
  | Banner
  | Order
  | Product
  | Brand
  | Category
  | BlockContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;

// Source: app/[lang]/(client)/(user)/success/page.tsx
// Variable: query
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){  ...,products[]{    ...,product->  }}
export type QueryResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      description?: string;
      price?: number;
      discount?: number;
      categories?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "category";
      }>;
      stock?: number;
      brand?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "brand";
      };
      status?: "hot" | "new" | "sale";
      variant?: "Dark Roast" | "Extra Dark" | "Light Roast" | "Medium Roast";
      isFeatured?: boolean;
      averageRating?: number;
      totalReviews?: number;
      ratingDistribution?: {
        fiveStars?: number;
        fourStars?: number;
        threeStars?: number;
        twoStars?: number;
        oneStar?: number;
      };
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "address_confirmed"
    | "cancelled"
    | "completed"
    | "delivered"
    | "failed_delivery"
    | "order_confirmed"
    | "out_for_delivery"
    | "packed"
    | "pending"
    | "ready_for_delivery"
    | "rescheduled";
  orderDate?: string;
  paymentStatus?: "cancelled" | "failed" | "paid" | "pending";
  paymentMethod?: "card" | "cash_on_delivery" | "stripe";
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "confirmed" | "not_submitted" | "pending" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?:
      | "accounts"
      | "admin"
      | "callcenter"
      | "deliveryman"
      | "incharge"
      | "packer"
      | "system"
      | "warehouse";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
}>;

// Source: sanity/helpers/index.ts
// Variable: PRODUCT_BY_CATEGORY_QUERY
// Query: *[_type == 'product' && references(*[_type == "category" && slug.current == $categorySlug]._id)] | order(name asc)
export type PRODUCT_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  status?: "hot" | "new" | "sale";
  variant?: "Dark Roast" | "Extra Dark" | "Light Roast" | "Medium Roast";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;

// Source: sanity/helpers/index.ts
// Variable: BANNER_QUERY
// Query: *[_type == 'banner'] | order(weight asc, title asc){      ...,      backgroundVideo{        asset->{          url        }      },      "backgroundVideoUrl": backgroundVideo.asset->url    }
export type BANNER_QUERY_RESULT = Array<{
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  backgroundVideo: null;
  backgroundVideoUrl: null;
}>;

// Source: sanity/helpers/index.ts
// Variable: SALE_QUERY
// Query: *[_type == 'sale'] | order(name asc)
export type SALE_QUERY_RESULT = Array<never>;

// Source: sanity/helpers/index.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc)[$start...$end]{    ...,    paymentStatus,    paymentMethod,    products[]{      ...,      product->{        _id,        name,        slug,        image,        images,        price,        currency      }    }  }
export type MY_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      image: null;
      images: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }> | null;
      price: number | null;
      currency: null;
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "address_confirmed"
    | "cancelled"
    | "completed"
    | "delivered"
    | "failed_delivery"
    | "order_confirmed"
    | "out_for_delivery"
    | "packed"
    | "pending"
    | "ready_for_delivery"
    | "rescheduled";
  orderDate?: string;
  paymentStatus: "cancelled" | "failed" | "paid" | "pending" | null;
  paymentMethod: "card" | "cash_on_delivery" | "stripe" | null;
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "confirmed" | "not_submitted" | "pending" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?:
      | "accounts"
      | "admin"
      | "callcenter"
      | "deliveryman"
      | "incharge"
      | "packer"
      | "system"
      | "warehouse";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
}>;

// Source: sanity/helpers/index.ts
// Variable: COUNT_QUERY
// Query: count(*[_type == 'order' && clerkUserId == $userId])
export type COUNT_QUERY_RESULT = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){\n  ...,products[]{\n    ...,product->\n  }\n}": QueryResult;
    "*[_type == 'product' && references(*[_type == \"category\" && slug.current == $categorySlug]._id)] | order(name asc)": PRODUCT_BY_CATEGORY_QUERY_RESULT;
    "*[_type == 'banner'] | order(weight asc, title asc){\n      ...,\n      backgroundVideo{\n        asset->{\n          url\n        }\n      },\n      \"backgroundVideoUrl\": backgroundVideo.asset->url\n    }": BANNER_QUERY_RESULT;
    "*[_type == 'sale'] | order(name asc)": SALE_QUERY_RESULT;
    "*[_type == 'order' && clerkUserId == $userId] | order(orderDate desc)[$start...$end]{\n    ...,\n    paymentStatus,\n    paymentMethod,\n    products[]{\n      ...,\n      product->{\n        _id,\n        name,\n        slug,\n        image,\n        images,\n        price,\n        currency\n      }\n    }\n  }": MY_ORDERS_QUERY_RESULT;
    "count(*[_type == 'order' && clerkUserId == $userId])": COUNT_QUERY_RESULT;
  }
}
